name: tomato_classifier
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy=2.3.5
  - pandas=3.0.0
  - scipy=1.17.0
  - scikit-learn=1.8.0
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - pyyaml=6.0.3
  - openpyxl=3.1.5
  - joblib=1.5.3
  - ipython=9.7.0
  - pytest=8.4.2
  - pip
  - pip:
      - shap==0.50.0
      - nbformat==5.10.4
